version: "3.10"

services:
  app:
    build: .
    restart: always
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    command: >
      sh -c "flask run --host=0.0.0.0 --port=8001 --debug"
