version: "3.11"

services:
  app:
    build: .
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: >
      sh -c "flask run --host=0.0.0.0 --port=8000 --debug"
